# NumPy Tutorial for Beginners

**NumPy** (Numerical Python) is a powerful library for numerical computations in Python. It supports large multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.

In [ ]:
# !pip install numpy

## Importing NumPy

In [10]:
import numpy as np

## Creating Arrays
### From Python List

In [12]:
arr = np.array([1, 2, 3])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


### 2D Array (Matrix)

In [14]:
arr2d = np.array([[1, 2], [3, 4]])
print(arr2d)
print(arr2d.shape)

[[1 2]
 [3 4]]
(2, 2)


## Array Properties

In [15]:
print("Shape:", arr2d.shape)  # this is a 2 * 2 matrix
print("Size:", arr2d.size) # gives total number of elements in the array
print("Data type:", arr2d.dtype) # data types of the elements in the array 

Shape: (2, 2)
Size: 4
Data type: int64


## Array Creation Functions

In [16]:
print(np.zeros((2, 3)))  ## create numpy array of size 2 * 3 with all value = 0
print()
print(np.ones((2, 2)))  ## create numpy array of size 2 * 2 with all value = 1
print()
print(np.full((2, 2), 5))  ## create numpy array of size 2 * 2 with all value = 5

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]]

[[5 5]
 [5 5]]


In [17]:
print(np.eye(3))    ## create an identity matrix of size 3 * 3
print()
print(np.arange(0, 10, 2))  ## arange(start, stop, step) --> then into the 1d array
print()
print(np.linspace(0, 1, 5))  ## linspace(start, stop, no. of division)
print()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]



## Indexing and Slicing

In [18]:
a = np.array([10, 20, 30, 40])
print(a)
print(a[1])  ## 20
print(a[1:3]) ## [20 30]

[10 20 30 40]
20
[20 30]


In [20]:
print('Indexing in b matrix')
b = np.array([[1, 2, 3, 4, 5], [4, 5, 6, 7, 8], [11, 12, 13, 14, 15]])
print(b)
print()
print(b[1, 2])  
print()
print(b[:, 1]) 

Indexing in b matrix
[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [11 12 13 14 15]]

6

[ 2  5 12]


In [21]:
b[0:2, 2]

array([3, 6])

## Basic Operations

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(a ** 2)
print(np.dot(a, b))  ## 1 * 4 + 2 * 5 + 3 * 6 = 4 + 10 + 18 = 32

[5 7 9]
[ 4 10 18]
[1 4 9]
32


## Useful Functions

In [23]:
a = np.array([1, 2, 3, 12, 14, 15, 16, 12, 13])
print(np.mean(a))   ## obtain the mean of the array
print(np.median(a))  ## obtain the median of the array
print(np.std(a)) ## obtain the standard deviation of the array
print(np.max(a)) ## obtain the max value of the array
print(np.min(a)) ## obtain the min value of the array

9.777777777777779
12.0
5.6524877075452915
16
1


## Reshaping and Flattening

In [24]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr)

reshaped = arr.reshape((2, 3))  ## reshape the 3 * 2 matrix into 2 * 3 matrix
flattened = arr.flatten() ## convert 2d matrix into 1d matrix.

print("Reshaped:\n", reshaped)
print("Flattened:", flattened)

[[1 2]
 [3 4]
 [5 6]]
Reshaped:
 [[1 2 3]
 [4 5 6]]
Flattened: [1 2 3 4 5 6]


In [25]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr)


[[1 2]
 [3 4]
 [5 6]]


In [26]:
print(arr.T)

[[1 3 5]
 [2 4 6]]


## Random Module

In [27]:
print(np.random.rand(2, 3))  ## create 2 * 2 matrix and fill elements with random numbers


[[0.43313434 0.52674378 0.31686007]
 [0.43670991 0.23406475 0.07976941]]


In [28]:
arr = np.random.randint(1, 100, 10)
print(arr)

[77 84 98 66 22 15 44 33 73 60]


## Exercise
**Task**: Create a 1D NumPy array of 10 random integers between 1 and 100. Find its mean, max, and sort the array.

In [28]:
arr = np.random.randint(1, 100, 10)
print("Array:", arr)
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Sorted:", np.sort(arr))

Array: [75 52 42 16 32 12 59 42 89 75]
Mean: 49.4
Max: 89
Sorted: [12 16 32 42 42 52 59 75 75 89]
